version: '2'
services:
  mysql:
    image: mysql:$MYSQL_V
    restart: $RESTART_POLICY
    environment:
      MYSQL_DATABASE : $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - /home/webmaster/$VIRTUAL_HOST/mysql:/var/lib/mysql
      #- $PATH/$PROJECT_NAME//init_sql:/docker-entrypoint-initdb.d
    network_mode: bridge
  web:
    image: mindengineering/amp-stack:$PHP_V
    depends_on:
      - mysql
    restart: $RESTART_POLICY
    hostname: $VIRTUAL_HOST
    links:
      - mysql:mysql
    volumes:
      - /home/webmaster/$VIRTUAL_HOST/public_html:/var/www/html
    environment:
      VIRTUAL_HOST: $VIRTUAL_HOST
      #LETSENCRYPT_HOST: $APACHE_PUBLIC_DIRECTORY
      #LETSENCRYPT_EMAIL: mindengineering.tn@gmail.com
      APACHE_PUBLIC_DIRECTORY: $APACHE_PUBLIC_DIRECTORY
    #ports:
    #  - 80:80
    #  - 587:587
    network_mode: bridge
